# typed: false
# frozen_string_literal: true

# This file is generated by the cctop release workflow. DO NOT EDIT.
class Cctop < Formula
  desc "Live top-style monitor for Claude Code sessions"
  homepage "https://github.com/stefanprodan/cctop"
  version "LATEST_RELEASE"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stefanprodan/cctop/releases/download/vLATEST_RELEASE/cctop_darwin_amd64.tar.gz"
      sha256 "CCTOP_DARWIN_AMD64"

      define_method(:install) do
        bin.install "cctop"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stefanprodan/cctop/releases/download/vLATEST_RELEASE/cctop_darwin_arm64.tar.gz"
      sha256 "CCTOP_DARWIN_ARM64"

      define_method(:install) do
        bin.install "cctop"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/stefanprodan/cctop/releases/download/vLATEST_RELEASE/cctop_linux_amd64.tar.gz"
      sha256 "CCTOP_LINUX_AMD64"

      define_method(:install) do
        bin.install "cctop"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stefanprodan/cctop/releases/download/vLATEST_RELEASE/cctop_linux_arm64.tar.gz"
      sha256 "CCTOP_LINUX_ARM64"

      define_method(:install) do
        bin.install "cctop"
      end
    end
  end

  test do
    system bin/"cctop", "--version"
  end
end
