# typed: false
# frozen_string_literal: true

# This file is generated by the cctop release workflow. DO NOT EDIT.
class Cctop < Formula
  desc "Live top-style monitor for Claude Code sessions"
  homepage "https://github.com/stefanprodan/cctop"
  version "0.9.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stefanprodan/cctop/releases/download/v0.9.0/cctop_darwin_amd64.tar.gz"
      sha256 "f885c62b43edb1c9a160727dcdb7a6266bda008ff3aec56b9e4ddb9631736f3a"

      define_method(:install) do
        bin.install "cctop"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stefanprodan/cctop/releases/download/v0.9.0/cctop_darwin_arm64.tar.gz"
      sha256 "8266e89c88d9b9035796b50e82049fdc12f62e0560cd597f58da8b19417f477c"

      define_method(:install) do
        bin.install "cctop"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/stefanprodan/cctop/releases/download/v0.9.0/cctop_linux_amd64.tar.gz"
      sha256 "efb775b62b724203acd526d6a7403caf2caad94d5071dac592683214b99fc5d1"

      define_method(:install) do
        bin.install "cctop"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stefanprodan/cctop/releases/download/v0.9.0/cctop_linux_arm64.tar.gz"
      sha256 "69c34956e136b65f359185e8c1d9e889fb1a41378dadd0f5787f7643651c71eb"

      define_method(:install) do
        bin.install "cctop"
      end
    end
  end

  test do
    system bin/"cctop", "--version"
  end
end
