# typed: false
# frozen_string_literal: true

# This file is generated by the cctop release workflow. DO NOT EDIT.
class Cctop < Formula
  desc "Live top-style monitor for Claude Code sessions"
  homepage "https://github.com/stefanprodan/cctop"
  version "0.6.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stefanprodan/cctop/releases/download/v0.6.0/cctop_darwin_amd64.tar.gz"
      sha256 "51bfe5241f6050504354a945191c57561ff19a7bc306c9262b6d74d304310cb7"

      define_method(:install) do
        bin.install "cctop"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stefanprodan/cctop/releases/download/v0.6.0/cctop_darwin_arm64.tar.gz"
      sha256 "6516a9e32a4fcc61c7b64666928505e58bb761f286d047c11d6be9e5b1adf622"

      define_method(:install) do
        bin.install "cctop"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/stefanprodan/cctop/releases/download/v0.6.0/cctop_linux_amd64.tar.gz"
      sha256 "30cc42e59e9083c369f5c1b6419c6a5da4210f86d40e5d3468b8cda9cdda91b1"

      define_method(:install) do
        bin.install "cctop"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stefanprodan/cctop/releases/download/v0.6.0/cctop_linux_arm64.tar.gz"
      sha256 "166743ad3abd10aba8ab9e137d7c5c4b5340bfc75153ef2a94c57627f9f76c2f"

      define_method(:install) do
        bin.install "cctop"
      end
    end
  end

  test do
    system bin/"cctop", "--version"
  end
end
