# typed: false
# frozen_string_literal: true

# This file is generated by the timoni release workflow. DO NOT EDIT.
class Timoni < Formula
  desc "Package manager for Kubernetes powered by CUE"
  homepage "https://timoni.sh"
  version "LATEST_RELEASE"
  license "Apache-2.0"

  depends_on "cue" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stefanprodan/timoni/releases/download/vLATEST_RELEASE/timoni_LATEST_RELEASE_darwin_amd64.tar.gz"
      sha256 "TIMONI_DARWIN_AMD64"

      define_method(:install) do
        bin.install "timoni"
        bash_output = Utils.safe_popen_read(bin/"timoni", "completion", "bash")
        (bash_completion/"timoni").write bash_output
        zsh_output = Utils.safe_popen_read(bin/"timoni", "completion", "zsh")
        (zsh_completion/"_timoni").write zsh_output
        fish_output = Utils.safe_popen_read(bin/"timoni", "completion", "fish")
        (fish_completion/"timoni.fish").write fish_output
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stefanprodan/timoni/releases/download/vLATEST_RELEASE/timoni_LATEST_RELEASE_darwin_arm64.tar.gz"
      sha256 "TIMONI_DARWIN_ARM64"

      define_method(:install) do
        bin.install "timoni"
        bash_output = Utils.safe_popen_read(bin/"timoni", "completion", "bash")
        (bash_completion/"timoni").write bash_output
        zsh_output = Utils.safe_popen_read(bin/"timoni", "completion", "zsh")
        (zsh_completion/"_timoni").write zsh_output
        fish_output = Utils.safe_popen_read(bin/"timoni", "completion", "fish")
        (fish_completion/"timoni.fish").write fish_output
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/stefanprodan/timoni/releases/download/vLATEST_RELEASE/timoni_LATEST_RELEASE_linux_amd64.tar.gz"
      sha256 "TIMONI_LINUX_AMD64"

      define_method(:install) do
        bin.install "timoni"
        bash_output = Utils.safe_popen_read(bin/"timoni", "completion", "bash")
        (bash_completion/"timoni").write bash_output
        zsh_output = Utils.safe_popen_read(bin/"timoni", "completion", "zsh")
        (zsh_completion/"_timoni").write zsh_output
        fish_output = Utils.safe_popen_read(bin/"timoni", "completion", "fish")
        (fish_completion/"timoni.fish").write fish_output
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stefanprodan/timoni/releases/download/vLATEST_RELEASE/timoni_LATEST_RELEASE_linux_arm64.tar.gz"
      sha256 "TIMONI_LINUX_ARM64"

      define_method(:install) do
        bin.install "timoni"
        bash_output = Utils.safe_popen_read(bin/"timoni", "completion", "bash")
        (bash_completion/"timoni").write bash_output
        zsh_output = Utils.safe_popen_read(bin/"timoni", "completion", "zsh")
        (zsh_completion/"_timoni").write zsh_output
        fish_output = Utils.safe_popen_read(bin/"timoni", "completion", "fish")
        (fish_completion/"timoni.fish").write fish_output
      end
    end
  end

  test do
    system "#{bin}/timoni version"
  end
end
